// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('createUserCtrl', function($scope, $location, $rootScope, $http, userService) {
    return $scope.createUser = function() {
      var user;
      console.log('from create user');
      console.log($scope.data);
      if ($scope.data.username !== void 0 && $scope.data.password !== void 0 && $scope.data.confirmPassword !== void 0) {
        user = {
          id: _.max(userService.user_employer, function(user) {
            return user.id;
          }).id + 1,
          username: $scope.data.username,
          password: $scope.data.password
        };
        userService.user_employer.push(user);
        return console.log('successfully pushed into the user_employer');
      } else {
        return console.log('Please fill the details');
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=CreateUser.map
*/
