// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('CustomerLoginController', function($scope, $location, $http) {
    return $scope.customerViews = function() {
      console.log('coustomer login', $scope);
      return $location.path('/customerhome');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=CustomerLoginController.map
*/
