// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('CustomerLoginController', function($scope, $rootScope, $location, $http, userService) {
    $rootScope.admin = false;
    $rootScope.login = false;
    return $scope.customerViews = function(login) {
      console.log(login);
      if (login.admin && login.username === userService.user_admin.username && login.password === userService.user_admin.password) {
        console.log('admin success');
        $rootScope.admin = true;
        $rootScope.login = true;
        return $location.path('/home');
      } else {
        return _.filter(userService.user_employer, function(user) {
          if (user.username === login.username && user.password === login.password) {
            console.log('employee success');
            $location.path('/home');
            return $rootScope.login = true;
          } else {
            return $scope.userlogin = '';
          }
        });
      }
    };
  });

}).call(this);

//# sourceMappingURL=CustomerLoginController.map
