// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('CustomerProjectsListController', function($scope, $location) {});

}).call(this);

/*
//@ sourceMappingURL=CustomerProjectsListController.map
*/
