(angular.module 'reitz')
.controller 'CustomerProjectsListController',($scope,$location,Reitzresources,projectservice)->
  #$scope.projectslist = Reitzresources.fanproject.query()
  $scope.projectslist=[
    {
      "$id":"1",
      "Date":"2014-03-14",
      "Engineer":"Ravi",
      "ProjectName":"Reitz",
      "Proposal_OrderNo":"12",
      "LastUiFormCompleted":null,
      "Id":"6f269c1f-321c-4179-ab13-b3a7b5e761d1",
      "FanAssemblies":{
        "$id":"2",
        "Id":"08d52081-c18b-4aa4-8784-d91059303e69",
        "FanProjectId":"4ae1a933-b12c-4623-b43c-12722510c9b8",
        "EvaseOutlet_InletAreaRatio":1.12,
        "OutletSilencer":0,
        "OutletOtherParts":0,
        "InletSoundSilencer":0,
        "InletBox":0.3,
        "InletOtherParts":0.2,
        "PressureDifference":0,
        "FanProject":{
          "$ref":"1"
        },
        "EntityKey":{
          "$id":"3",
          "EntitySetName":"FanAssemblies",
          "EntityContainerName":"FanalytixEntities",
          "EntityKeyValues":[
            {
              "Key":"Id",
              "Type":"System.Guid",
              "Value":"324e617e-b281-49dd-ab17-ba4e7261c76e"
            }
          ]
        }
      },
      "FanTypes":[
      ],
      "GasDatas": {
        "$id":"4",
        "BarometricPressure_Elevation":0,
        "GasDustload":0,
        "Id":"704e816e-130f-4761-80a8-79dad3b9f74f",
        "FanProjectId":"24faa3a6-7dde-41e3-9fcf-93468d455eab",
        "VpUnit":1,
        "DptUnit":1,
        "FanProject":{
          "$ref":"1"
        },
        "EntityKey":{
          "$id":"5",
          "EntitySetName":"GasDatas",
          "EntityContainerName":"FanalytixEntities",
          "EntityKeyValues":[
            {
              "Key":"Id",
              "Type":"System.Guid",
              "Value":"b7fb0f5f-1c86-4371-8b71-36d7d233744a"
            }
          ]
        }
      },
      GasOperatingPoints:[
        {
          "$id":"11",
          "T":89,
          "Dpt":5676,
          "P1":0,
          "F":0.90,
          "Ro":0.874
          "Id":"65cf4f6f-348d-4851-bac8-8d502f41c64e",
          "GasDataId":"55182f7c-864c-42e5-8789-48a2ce9d4f74",
          "Vi":"21.05e-6",
          "Vp":155,
          "GasData":{
            "$ref":"4"
          }
        },{
          "$id":"11",
          "T":200,
          "Dpt":5676,
          "P1":10,
          "F":0.90,
          "Ro":0.900
          "Id":"65cf4f6f-348d-4851-bac8-8d502f41c64e",
          "GasDataId":"55182f7c-864c-42e5-8789-48a2ce9d4f74",
          "Vi":"21.05e-6",
          "Vp":155,
          "GasData":{
            "$ref":"4"
          }
        }
      ],
      "Noises":{
        "$id":"6",
        "RoomAbsorptionArea":0,
        "FanLocation":0,
        "BackgroundNoiseCorrection":0,
        "Design":0,
        "HousingMetalPlateThickness":0,
        "DistanceBetweenStiffners":null,
        "HousingMaterial":null,
        "Id":"ee733f9e-28d6-4232-90d6-2a53f5ad156a",
        "FanProjectId":"058aced4-1ff6-440d-8386-636a3f6f19bb",
        "FanProject":{
          "$ref":"1"
        },
        "EntityKey":{
          "$id":"7",
          "EntitySetName":"Noises",
          "EntityContainerName":"FanalytixEntities",
          "EntityKeyValues":[
            {
              "Key":"Id",
              "Type":"System.Guid",
              "Value":"353edefe-4715-4ad8-8b4e-fef4993b3bff"
            }
          ]
        }
      },
      "UnitValueForInputFields":[
      ],
      "MaterialDriveControls":{
        "$id":"8",
        "InletOutletDuct":2,
        "Width":2,
        "DesignType":null,
        "BackBlades":false,
        "Control":0,
        "IVCPosition":false,
        "MechanicalDesignTemperature":150,
        "StandardImpellerMaterial":true,
        "MaterialName":null,
        "MaterialDensity":null,
        "MaterialYieldStrength":0,
        "IECStandardMotor":false,
        "NominalMotorSpeed":null,
        "MotorSpeed":null,
        "MotorPower":0,
        "Id":"df1d67d3-77f2-49e8-be1f-047802616862",
        "FanProjectId":"4b6b1af4-4e0e-4dea-bf9b-5ee184a5a962",
        "NoiseDataRequired":0,
        "Drive":"K",
        "FanProject":{
          "$ref":"1"
        },
        "EntityKey":{
          "$id":"9",
          "EntitySetName":"MaterialDriveControls",
          "EntityContainerName":"FanalytixEntities",
          "EntityKeyValues":[
            {
              "Key":"Id",
              "Type":"System.Guid",
              "Value":"033dc8fb-4832-4da8-8833-3f255d608f52"
            }
          ]
        }
      },
      "EntityKey":{
        "$id":"10",
        "EntitySetName":"FanProjects",
        "EntityContainerName":"FanalytixEntities",
        "EntityKeyValues":[
          {
            "Key":"Id",
            "Type":"System.Guid",
            "Value":"120e95f9-e656-43dd-b90c-05e73afc73bf"
          }
        ]
      }
    }
  ]
  $scope.sendData =(obj)->
    projectservice.editdata= obj
    $location.url '/newproject'