// Generated by CoffeeScript 1.6.3
(function() {
  var row;

  row = "  <tr>      <td ng-mouseenter='mode = 0'>        <span ng-show='mode == 1 '>{{data.GasOperatingPoints.T}} </span>        <input class='form-control' id='txtToolTip' ng-show='mode != 1' ng-model='data.GasOperatingPoints.T' autofocus='true' ng-enter/></td>       <td ng-mouseenter='mode = 0'>											<span ng-show='mode == 1'>{{data.GasOperatingPoints.Vp}}</span>											<select class='form-control' ng-show='mode == 1' ng-model='data.GasOperatingPoints.VpUnits' disabled ng-enter>												<option>{{VpUnits}}</option></select>											<input class='form-control' type='text' ng-show='mode != 1' ng-model='data.GasOperatingPoints.Vp' ng-enter/>											<select class='form-control' ng-show='mode != 1' ng-model='data.GasOperatingPoints.VpUnits' ng-enter>												<option ng-selected='true'> M3/S </option>												<option>M3/M</option>												<option> M3/H</option>												<option> NM3/S</option>												<option> NM3/M</option>												<option> NM3/H</option>												</select>												</td>       </tr> ";

  (angular.module('reitz')).directive('ngEnter', function($compile) {
    return function($scope, elem, attrs) {
      return elem.bind('keypress', function(e) {
        console.log(elem);
        if (e.keyCode === 13 && elem.siblings()) {
          if (elem.parent().next().children().length === 4) {
            return elem.parent().next().children()[2].focus();
          } else {
            return elem.parent().next().find('input').focus();
          }
          /* contentTr = angular.element('<tr><td><input/></td></tr>')
          contentTr.insertBefore(elem.parents().find('tbody').find('tr')[0])
          $compile(contentTr)($scope)
          */

        } else if (e.keyCode === 13 && elem.parents()) {
          elem.parents('td').next().find('input[type=text]').focus();
          return console.log(elem.parents('td').next().find('input[type=text]'));
        }
      });
    };
  }).directive('ngAddrow', function($compile) {
    return function($scope, elem, attrs) {
      return elem.bind('keypress', function(e) {
        var contentTr;
        if (e.keyCode === 13) {
          contentTr = angular.element(row);
          contentTr.insertBefore(elem.parents().find('tbody').find('tr')[0]);
          return $compile(contentTr)($scope);
        }
      });
    };
  });

}).call(this);

/*
//@ sourceMappingURL=EnterKeyDirective.map
*/
