// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('fanAssemblingController', function($scope, $route, $location, $rootScope, projectservice, ReitzResources, chartService) {
    $scope.data = projectservice.data;
    $scope.inletSilencer = ReitzResources.multiunitsdata.query();
    $scope.lines = {
      faninlet: false,
      fanoutlet: false,
      onlyfan: false,
      onlyinlet: false
    };
    $scope.$watch('data.FanAssemblies.PressureDifference', (function(value) {
      if (value === '1') {
        $scope.lines.fanoutlet = true;
        $scope.lines.faninlet = false;
        $scope.lines.onlyinlet = true;
        return $scope.lines.onlyfan = false;
      } else if (value === '2') {
        $scope.lines.faninlet = true;
        $scope.lines.fanoutlet = false;
        return $scope.lines.onlyfan = false;
      } else if (value === '3') {
        $scope.lines.fanoutlet = true;
        $scope.lines.faninlet = true;
        return $scope.lines.onlyfan = true;
      } else {
        $scope.lines.fanoutlet = false;
        $scope.lines.faninlet = false;
        $scope.lines.onlyinlet = false;
        return $scope.lines.onlyfan = false;
      }
    }), true);
    $scope.operatingPoint = function() {
      return $location.path('/operatingPoint');
    };
    return $scope.materialControl = function() {
      return $location.path('/materialControl');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=fanAssemblingController.map
*/
