// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('HomeController', function($scope, $location) {
    return $scope.customerViews = function() {
      return $location.url('/projectdata');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=HomeController.map
*/
