// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('NewProjectController', function($scope, $location, projectservice, chartService) {
    $scope.mode = 0;
    $scope.data = projectservice.data;
    $scope.$watch('data.MaterialDriveControls.MechanicalDesignTemperature', (function() {
      if ($scope.data.MaterialDriveControls.MechanicalDesignTemperature > 350) {
        return $scope.data.MaterialDriveControls.StandardImpellerMaterial = false;
      } else {
        return $scope.data.MaterialDriveControls.StandardImpellerMaterial = true;
      }
    }), true);
    $scope.$watch('data.MaterialDriveControls.Drive', (function() {
      if ($scope.data.MaterialDriveControls.Drive === "K") {
        $scope.data.MaterialDriveControls.direct = true;
        return $scope.data.MaterialDriveControls.IECStandardMotor = false;
      } else {
        $scope.data.MaterialDriveControls.direct = false;
        return $scope.data.MaterialDriveControls.IECStandardMotor = true;
      }
    }), true);
    $scope.$watch('data.GasOperatingPoints.T', (function() {
      return $scope.data.GasOperatingPoints.Vi = projectservice.density($scope.data.GasOperatingPoints.T);
    }), true);
    $scope.$watch('data.MaterialDriveControls.Control', (function() {
      if ($scope.data.MaterialDriveControls.Control === "1") {
        return $scope.data.MaterialDriveControls.IVCPosition = true;
      } else {
        return $scope.data.MaterialDriveControls.IVCPosition = false;
      }
    }), true);
    $scope.lines = {
      faninlet: false,
      fanoutlet: false,
      onlyfan: false,
      onlyinlet: false
    };
    $scope.chb = {
      At: true,
      Ro: false
    };
    $scope.$watch('data.GasOperatingPoints.Atcheck', (function() {
      if ($scope.data.GasOperatingPoints.Atcheck) {
        $scope.chb.At = false;
        $scope.chb.Ro = true;
        return $scope.data.GasOperatingPoints.Alt = null;
      } else {
        $scope.chb.At = true;
        $scope.chb.Ro = false;
        return $scope.data.GasOperatingPoints.Ro = null;
      }
    }), true);
    $scope.$watch('data.FanAssemblies.PressureDifference', (function() {
      if ($scope.data.FanAssemblies.PressureDifference === '1') {
        $scope.lines.fanoutlet = true;
        $scope.lines.faninlet = false;
        $scope.lines.onlyinlet = true;
        return $scope.lines.onlyfan = false;
      } else if ($scope.data.FanAssemblies.PressureDifference === '2') {
        $scope.lines.faninlet = true;
        $scope.lines.fanoutlet = false;
        return $scope.lines.onlyfan = false;
      } else if ($scope.data.FanAssemblies.PressureDifference === '3') {
        $scope.lines.fanoutlet = true;
        $scope.lines.faninlet = true;
        return $scope.lines.onlyfan = true;
      } else {
        $scope.lines.fanoutlet = false;
        $scope.lines.faninlet = false;
        $scope.lines.onlyinlet = false;
        return $scope.lines.onlyfan = false;
      }
    }), true);
    $scope.createProject = function(data) {
      $scope.data.GOPoints.push($scope.data.GasOperatingPoints);
      chartService.postdata = $scope.data;
      return $location.path('/chartview');
    };
    $scope.addOperatingPoint = function() {
      $scope.data.GOPoints.push($scope.data.GasOperatingPoints);
      return $scope.data.GasOperatingPoints = {
        T: 0
      };
    };
    $scope.calculateVp = function() {};
    $scope.CalcNormalDensity = function() {};
    return $scope.calculateDensity = function() {
      var Alt, T, condition, operate;
      condition = $scope.data.GasDatas.DptUnits;
      operate = $scope.data.GasOperatingPoints.Dpt;
      Alt = $scope.data.GasOperatingPoints.Alt;
      T = $scope.data.GasOperatingPoints.T;
      return $scope.data.GasOperatingPoints.Ro = projectservice.calculateDensity(condition, operate, Alt, T);
    };
  });

}).call(this);

/*
//@ sourceMappingURL=NewProjectController.map
*/
