// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('noiseDataController', function($scope, $route, $location, $rootScope, projectservice, ReitzResources, chartService) {
    $scope.data = projectservice.data;
    $scope.materialControl = function() {
      return $location.path('/materialControl');
    };
    return $scope.createProject = function(data) {
      $scope.data.GasOperatingPoints.push($scope.data.GasOperatingPoint);
      chartService.postdata = $scope.data;
      $scope.data = null;
      return $location.path('/chartview');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=noiseDataController.map
*/
