// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('OperatingPointsController', function($scope, $route, $location, $rootScope, projectservice, ReitzResources, chartService) {
    $scope.data = projectservice.data;
    $scope.opbtn = true;
    $scope.$watch('data.GasOperatingPoint.T', (function(value) {
      return $scope.data.GasOperatingPoint.Vi = projectservice.density(value);
    }), true);
    $scope.chb = {
      At: true,
      Ro: false
    };
    $scope.$watch('data.GasOperatingPoint.Atcheck', (function(value) {
      if (value) {
        $scope.chb.At = false;
        $scope.chb.Ro = true;
        return $scope.data.GasOperatingPoint.Alt = null;
      } else {
        $scope.chb.At = true;
        $scope.chb.Ro = false;
        return $scope.data.GasOperatingPoint.Ro = null;
      }
    }), true);
    $scope.addOperatingPoint = function(dummy) {
      if (dummy === void 0) {
        $scope.data.GasOperatingPoints.push($scope.data.GasOperatingPoint);
        return $scope.data.GasOperatingPoint = {
          T: 0,
          F: 0,
          P1: 0
        };
      } else {
        $scope.data.GasOperatingPoints[dummy] = $scope.data.GasOperatingPoint;
        return $scope.data.GasOperatingPoint = {
          T: 0
        };
      }
    };
    $scope.showGoPoints = function(op, index) {
      $scope.opbtn = false;
      $scope.indexSet = index;
      return $scope.data.GasOperatingPoint = op;
    };
    $scope.updateGoPoint = function() {
      $scope.opbtn = true;
      return $scope.addOperatingPoint($scope.indexSet);
    };
    $scope.calculateDensity = function() {
      var Alt, T, condition, operate;
      condition = $scope.data.GasDatas.DptUnits;
      operate = $scope.data.GasOperatingPoint.Dpt;
      Alt = $scope.data.GasOperatingPoint.Alt;
      T = $scope.data.GasOperatingPoint.T;
      return $scope.data.GasOperatingPoint.Ro = projectservice.calculateDensity(condition, operate, Alt, T);
    };
    $scope.projectInfo = function() {
      return $location.path('/newproject');
    };
    return $scope.fanAssembling = function() {
      return $location.path('/fanAssembling');
    };
  });

}).call(this);

//# sourceMappingURL=OperatingPointsController.map
