// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('ProjectDataController', function($scope, $route, $location, $rootScope, projectservice) {
    $scope.data = projectservice.data;
    $scope.projectInfo = function() {
      return $location.path('/newproject');
    };
    return $scope.operatingPoint = function() {
      return $location.path('/operatingPoint');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=ProjectDataController.map
*/
