// Generated by CoffeeScript 1.6.3
(function() {
  var $reportViewer, prevPageHeight, setHeight;

  setHeight = function() {
    var prevPageHeight;
    $("#reportViewer1").height(window.innerHeight);
    prevPageHeight = window.innerHeight;
  };

  prevPageHeight = 0;

  setInterval((function() {
    if (window.innerHeight !== prevPageHeight) {
      setHeight();
    }
  }), 500);

  setHeight();

  $reportViewer = $("#reportViewer1").telerik_ReportViewer({
    serviceUrl: "http://192.168.0.160/ReportService/api/reports/",
    templateUrl: "ReportViewer/templates/telerikReportViewerTemplate.html",
    reportSource: {
      report: "Sankar.trdx"
    },
    parameters: {
      addressid: 2
    }
  });

}).call(this);

/*
//@ sourceMappingURL=ReportController.map
*/
