// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).factory('projectservice', function() {
    var G, data, entitykey, generateId, guid;
    data = {};
    generateId = function() {
      var id;
      id = 0;
      return function() {
        return id++;
      };
    };
    G = function() {
      return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
    };
    guid = function() {
      return (G() + G() + "-" + G() + "-" + G() + "-" + G() + "-" + G() + G() + G()).toUpperCase();
    };
    return entitykey = function(keyname) {
      return {
        $id: generateId(),
        EntitySetName: kyename,
        EntityContainerName: "FanalytixEntities",
        EntityKeyValues: [
          {
            Key: "Id",
            Type: "System.Guid",
            Value: guid()
          }
        ]
      };
    };
  });

}).call(this);

/*
//@ sourceMappingURL=projectservice.map
*/
