// Generated by CoffeeScript 1.6.3
(function() {
  var indexView, partialViews;

  indexView = function(req, res) {
    return res.render('index');
  };

  partialViews = function(req, res) {
    var viewName;
    viewName = req.params.name;
    return res.render('customer/' + viewName);
  };

  module.exports = {
    index: indexView,
    customer: partialViews
  };

}).call(this);

/*
//@ sourceMappingURL=routes.map
*/
